#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'py-action-pkg==0.0.0','console_scripts','odom_sub_node'
__requires__ = 'py-action-pkg==0.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('py-action-pkg==0.0.0', 'console_scripts', 'odom_sub_node')()
    )
