omo_r1mini_node:
  ros__parameters:
    port:
      name: "/dev/ttyMCU"
      baudrate: 115200

    wheel:
      separation: 0.17
      radius: 0.0335

    motor:
      gear_ratio: 213

    sensor:
      enc_pulse: 44

diff_drive_controller:
  ros__parameters:
    odometry:
      frame_id: "odom"
      child_frame_id: "base_footprint"
